### ISSUE TITLE
'requirejs' is undefined

### ISSUE THREAD

**Issue by Cleanshooter** [mixxen/sails-react-example#1]
When I pull this and launch I get the following JavaScript errors:
SCRIPT12030: WebSocket Error: Network Error 12030, The connection with the server was terminated abnormally
SCRIPT5009: 'requirejs' is undefined

**Comment by clay-to-n** [comment]
I cloned the repo, did a `sudo npm` install and a `sails lift`, and I get the same error.

I'm on Chrome, v 41.0.2272.118.

**Comment by mixxen** [comment]
Do you have bower installed? Did you run ```bower install```?

**Comment by clay-to-n** [comment]
Apparently I didn't!  Everything works fine now with a bower install.

**Comment by longph92** [comment]
Hi mixxen, I had ran your demo and everything works perfect. Now I trying to init the new demo but I can't do that. So could you define the way for init the new project step by step? thank you so much :)

**Comment by mixxen** [comment]
@longph92 What error are you seeing?

**Comment by longph92** [comment]
@mixxen the error is: "requirejs is not defined", please help me to fix it :( Thank you so much for your quick reply :)
![screen shot 2015-06-13 at 11 50 58 am](https://cloud.githubusercontent.com/assets/11539342/8143042/7ed4561e-11c2-11e5-89fd-d52c3a1a967a.png)

**Comment by mixxen** [comment]
@longph92 maybe require.js is not being including in layout.ejs. see:

https://github.com/mixxen/sails-react-example/blob/master/views/layout.ejs#L92

**Comment by longph92** [comment]
@mixxen I have already included the require.js in layout.js, but I that still throw the undefined error :( Did you config anything in sails project?? for include the require.js ??

**Comment by mixxen** [comment]
@longph92 I don't think anything special config was done for requirejs in sails v0.10. Make sure require.js is included before the app code. If you want more help, you should probably push your code on github somewhere.
