### ISSUE TITLE
it looks like not work?

### ISSUE THREAD

**Issue by shoutleafy** [mixxen/sails-react-example#4]
git clone and intall package,
then run "node app.js" ,
sails was running
but where are some files like "/bower_components/todomvc-common/base.js"

this question is from a noob , so ... thank u ^ ^

**Comment by mixxen** [comment]
looks like you need to install bower: https://bower.io/

Run:

```
npm install -g bower
bower install
```

**Comment by shoutleafy** [comment]
that's right.
thk & best wishes
